28.0b1

diff --git a/pkg/erase-install/scripts/postinstall b/pkg/erase-install/scripts/postinstall
--- a/pkg/erase-install/scripts/postinstall
+++ b/pkg/erase-install/scripts/postinstall
@@ -10,25 +10,17 @@ DIR=$(dirname "$0")
 dialog_app="/Library/Application Support/Dialog/Dialog.app"
 dialog_bin="/usr/local/bin/dialog"
 
-if [[ ! -f "$dialog_bin" || ! -d "$dialog_app" ]]; then
-    echo "swiftDialog not found. Installing..."
-    if /usr/sbin/installer -tgt / -pkg "$DIR/dialog.pkg"; then
-        echo "swiftDialog successfully installed"
-    else
-        echo "ERROR: swiftDialog was not installed"
-        exit 1
-    fi
+if /usr/sbin/installer -tgt / -pkg "$DIR/dialog.pkg"; then
+    echo "swiftDialog successfully installed"
+else
+    echo "ERROR: swiftDialog was not installed"
+    exit 1
 fi
 
 # mist-cli
-mist_bin="/usr/local/bin/mist"
-
-if [[ ! -f "$mist_bin" ]]; then
-    echo "mist-cli not found. Installing..."
-    if /usr/sbin/installer -tgt / -pkg "$DIR/mist-cli.pkg"; then
-        echo "mist-cli successfully installed"
-    else
-        echo "ERROR: mist-cli was not installed"
-        exit 1
-    fi
+if /usr/sbin/installer -tgt / -pkg "$DIR/mist-cli.pkg"; then
+    echo "mist-cli successfully installed"
+else
+    echo "ERROR: mist-cli was not installed"
+    exit 1
 fi
